---
title: "BIS15L_project"
author: "Jaskirat, Mariana"
date: "2024-03-06"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Install Library 
```{r}
#install.packages("tidyverse")
#install.packages("janitor")
```


#Load Library
```{r}
library(tidyverse)
library(janitor)
library(paletteer)
library(ggthemes)
```


#Import Data
```{r}
health_data <- read_csv("data/ss.csv")
health_data <- clean_names(health_data)
```
```{r}
colors <- paletteer::palettes_d_names
```

```{r}
my_palette <- paletteer_d("awtools::bpalette")
```

#Effects of occupation on sleep duration
```{r}
health_data %>% 
  group_by(occupation) %>% 
  summarize(average_sleep_duration=mean(sleep_duration)) %>% 
  ggplot(aes(x=occupation, y=average_sleep_duration, fill=occupation))+
  geom_col()+
  scale_fill_manual(values=my_palette)+
  theme_light()+
  coord_flip()+
  labs(title="Average Sleep Duration Ranges For Various Occupations",
       x="Occupation", 
       y="Average Sleep Duration (hrs)", 
       fill="Occupation")
```


```{r}
health_data %>% 
  ggplot(aes(x=occupation, y=sleep_duration, fill=occupation))+
  geom_boxplot()+
  scale_fill_manual(values=my_palette)+
  theme_light()+
  labs(title="Average Sleep Duration Ranges For Various Occupations",
       x="Occupation", 
       y="Sleep Duration (hrs)", 
       fill="Occupation")+
  theme(axis.text.x=element_text(angle=60,hjust=1))
```
#Count
```{r}
health_data %>% 
  count(occupation, sort=T)
```

# Top 5 occupations in dataset

```{r}
selected_data <- health_data %>% 
  filter(occupation=="Nurse"| occupation=="Doctor"| occupation=="Engineer"| occupation=="Lawyer"| occupation=="Teacher")
selected_data
```

# Age range in data
```{r}
selected_data %>% 
  ggplot(aes(x=occupation, y=age, fill=occupation))+
  geom_boxplot()+
  scale_fill_manual(values=my_palette)+
  theme_light()+
  labs(title="Age Range of data in Various Occupations",
       x="Occupation", 
       y="Age", 
       fill="Occupation")+
  theme(axis.text.x=element_text(angle=60,hjust=1))
```



# Sleep duration vs quality of sleep 
```{r}
selected_data %>% 
  ggplot(aes(x=sleep_duration, y=quality_of_sleep, fill=occupation))+
  geom_col()+
  facet_wrap(~occupation)+
  scale_fill_manual(values=my_palette)+
  theme_light()+
  labs(title="Sleep Duration VS Quality of Sleep")
```

# Stress Levels based on occupation 
```{r}
selected_data %>% 
  ggplot(aes(x=stress_level, fill=occupation))+
  geom_bar()+
  facet_wrap(~occupation)+
  scale_fill_manual(values=my_palette)+
  theme_light()+
  labs(title="Stress Levels for Each Occupation")
```

# BMI category by occupation
```{r}
selected_data %>% 
  ggplot(aes(x=bmi_category, fill= occupation))+
  geom_bar(position = "dodge")+
  theme_light()+
  scale_fill_manual(values=my_palette)+
  labs(title="BMI Category by Occupation",
       x="BMI Category", 
       y="Number",
       fill="Occupation")
```
# Sleep disorders present in occupations?
```{r}
selected_data %>% 
  ggplot(aes(x=sleep_disorder, fill= occupation))+
  geom_bar(position = "dodge")+
  theme_light()+
  scale_fill_manual(values=my_palette)+
  labs(title="Sleep Disorders in Occupations",
       x="Sleep Disorder", 
       y="Number",
       fill="Occupation")
```

