---
title: "shiny_app"
output: html_document
date: "2024-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r, echo=FALSE}
#install.packages("shiny")
#install.packages("shinydashboard")
library(shiny)
library(tidyverse)
library(shinydashboard)
library(janitor)
```

Build a shiny app that allows users to select an occupation and see the health information based on that occupation. The app needs ui,server, and session$onSessionEnded(stopApp) to stop the app when we close it. 

```{r}
names(head(health_data))
```

```{r}
health_data <- read.csv("data/ss.csv") %>% clean_names()
```


#Creating categories for Numerical variables daily_steps and blood_pressure
```{r}
health_data %>% 
  mutate(daily_steps_category = case_when(
    daily_steps < 5000 ~ "Low",
    daily_steps >= 5000 & daily_steps < 10000 ~ "Moderate",
    daily_steps >= 10000 ~ "High"
  )) %>% 
  mutate(blood_pressure_category = case_when(
    blood_pressure < 120 ~ "Normal",
    blood_pressure >= 120 & blood_pressure < 130 ~ "Elevated",
    blood_pressure >= 130 & blood_pressure < 140 ~ "High Blood Pressure Stage 1",
    blood_pressure >= 140 ~ "High Blood Pressure Stage 2"
  )) -> health_data

```


```{r}
ui <- dashboardPage(
  
  dashboardHeader(title = "Health information based on Occupation"),
  
  dashboardSidebar(disable=T),
  
  dashboardBody(
    fluidRow(
      box( 
          selectInput("x", "Sleep Disorder", choices=unique(health_data$`sleep_disorder`)), hr()
),
box( 
    selectInput("y", "Select BMI Category", choices=unique(health_data$bmi_category)), hr()
    ),
    box( 
    selectInput("z", "Select Daily Steps", choices=unique(health_data$daily_steps_category)), hr()
    ),
box( 
    selectInput("a", "Select Daily Steps", choices=unique(health_data$blood_pressure_category)), hr()
    ),
box(width=7, 
    plotOutput("plot", width="600px", height="400px"))
    )
    ))


server <- function(input, output,session) {
  session$onSessionEnded(stopApp) #stops app when we close it
  
  output$plot <- renderPlot({
    health_data %>% 
      filter(sleep_disorder==input$x & bmi_category==input$y & daily_steps_category==input$z & blood_pressure_category==input$a) %>% 
      ggplot(aes(x=occupation, fill=gender))+
      geom_bar(position="dodge")+
      theme_light()+
      labs(title="Sleep Duration Ranges For Various Occupations",
           x="Occupation", 
           fill="Occupation")
  })
}


shinyApp(ui, server)

```


```{r}
ui <- dashboardPage(
  
  dashboardHeader(title = "Health information based on Occupation"),
  
  dashboardSidebar(disable=TRUE),
  
  dashboardBody(
    fluidRow(
      box( 
        selectInput("x", "Sleep Disorder", choices=c("All", unique(health_data$`sleep_disorder`))), hr()
      ),
      box( 
        selectInput("y", "Select BMI Category", choices=c("All", unique(health_data$bmi_category))), hr()
      ),
      box( 
        selectInput("z", "Select Daily Steps", choices=c("All", unique(health_data$daily_steps_category))), hr()
      ),
      box( 
        selectInput("a", "Select Blood Pressure Category", choices=c("All", unique(health_data$blood_pressure_category))), hr()
      ),
      box(width=7, 
        plotOutput("plot", width="600px", height="400px"))
    )
  )
)


server <- function(input, output, session) {
  session$onSessionEnded(stopApp) #stops app when we close it
  
  output$plot <- renderPlot({
    filtered_data <- health_data
    
    if(input$x != "All") {
      filtered_data <- filtered_data %>% filter(sleep_disorder == input$x)
    }
    if(input$y != "All") {
      filtered_data <- filtered_data %>% filter(bmi_category == input$y)
    }
    if(input$z != "All") {
      filtered_data <- filtered_data %>% filter(daily_steps_category == input$z)
    }
    if(input$a != "All") {
      filtered_data <- filtered_data %>% filter(blood_pressure_category == input$a)
    }
    
    filtered_data %>% 
      ggplot(aes(x=occupation, fill=gender))+
      geom_bar(position="dodge")+
      theme_light()+
      theme(axis.text.x=element_text(angle=90,hjust=1))+
      labs(title="Health Information by Occupation",
           x="Occupation", 
           fill="Gender")
  })
}


shinyApp(ui, server)
```


